type: array
items:
  type: object
  properties:
    companycode:
      type: string
      required: true
      example: "TTTTT"   
    orginLocation:
      type: string
      required: true
      example: "DEL-CHN"  
